// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_dotplot_data
DataFrame compute_dotplot_data(String r_s1, String r_s2, int wsize, int step, int n_mismatches);
RcppExport SEXP _dotplot_compute_dotplot_data(SEXP r_s1SEXP, SEXP r_s2SEXP, SEXP wsizeSEXP, SEXP stepSEXP, SEXP n_mismatchesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type r_s1(r_s1SEXP);
    Rcpp::traits::input_parameter< String >::type r_s2(r_s2SEXP);
    Rcpp::traits::input_parameter< int >::type wsize(wsizeSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< int >::type n_mismatches(n_mismatchesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_dotplot_data(r_s1, r_s2, wsize, step, n_mismatches));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dotplot_compute_dotplot_data", (DL_FUNC) &_dotplot_compute_dotplot_data, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_dotplot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
