# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_dotplot_data <- function(r_s1, r_s2, wsize, step, n_mismatches) {
    .Call(`_dotplot_compute_dotplot_data`, r_s1, r_s2, wsize, step, n_mismatches)
}

